remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Recode Leadership
description: Redefine Leadership, Empower Authenticity.
call_to_action: Book a Complimentary Career Strategy Call
call_to_action_link: https://forms.gle/Mb3ngWVDmRrAj8ueA
