remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Recode Leadership
description: Redefine Leadership, Empower Authenticity.
call_to_actions:
  - text: Schedule a Career Strategy Call
    link: https://forms.gle/Mb3ngWVDmRrAj8ueA
  - text: Book an Amplifying Your Strengths Session
    link: https://docs.google.com/document/d/1AszPFQlnYjo8iB_ZMEDf4kSBKofHspRiEgAz5a0kjeA/edit?usp_sharing
  - text: Download the Reground with Strengths Worksheet
    link: https://docs.google.com/document/d/1Ci-PnSw34yV9dL5pYFzEzbHxiGO2Wg28xwJ8j9sGgv8/edit?usp=sharing